In [25]:
# import the relevant packages

import calcos
from astropy.io import fits
import glob
import numpy as np

In [3]:
# set a variable "rawtags" to be all the files in my directory
# with the word "rawtag" in it

rawtags = glob.glob('*_rawtag_*.fits')

In [7]:
# printing the list of files set by the cell above

#print(rawtags)

In [6]:
# printing out the whole header of the first file (index [0])

#fits.getheader(rawtags[0])

In [8]:
# setting the 'RANDSEED' value to some number, here 123456789
# and using a for loop to apply this to every file

#fits.setval(rawtags[0], 'RANDSEED', value=123456789)

for myfile in rawtags:
    fits.setval(myfile, 'RANDSEED', value=123456789)

In [9]:
# print out the 'RANDSEED' value stipulated above
# in this case, the very last file in rawtags

fits.getval(myfile, 'RANDSEED')

123456789

In [11]:
# setting the various fits header parameters to what they need to be
# in order to run things well
# NB, the last four aren't even used, but it might save time later
# when we rul CalCOS on them

for myfile in rawtags:
    fits.setval(myfile, 'FLATCORR', value='OMIT')
    fits.setval(myfile, 'WAVECORR', value='OMIT')
    fits.setval(myfile, 'TRCECORR', value='OMIT')
    fits.setval(myfile, 'ALGNCORR', value='OMIT')
    fits.setval(myfile, 'XTRCTALG', value='BOXCAR')
    fits.setval(myfile, 'X1DCORR', value='PERFORM')
    fits.setval(myfile, 'BACKCORR', value='OMIT')
    fits.setval(myfile, 'FLUXCORR', value='OMIT')
    fits.setval(myfile, 'HELCORR', value='OMIT')

In [13]:
# reading the fits header information for extension 1
# looking for the keywords in Elaine's 2c

#fits.getheader(rawtags[0], ext=1)

In [14]:
# here I need to set these lamp flash parameters to match what the observations are doing
# the lamp is on for 30 seconds, then off for a while (depends on the exposure),
# so that it builds up signal without getting the lamp too hot

# the science exposures for G130M are 210 seconds, with 120 seconds of total lamp on time,
# while for G140L the science exposure length is 450 seconds, with 240 seconds of
# total lamp time

# also note that, at the beginning of each Visit, there's a single long exposure to settle
# the OSM, which is 1440 seconds for the two G130M Visits, but 1800 seconds for G140L

# here's an "if" statement that Elaine wrote as an example, which we've modified to fit:

for myfile in rawtags:
    if fits.getval(myfile, 'OPT_ELEM') == 'G130M' and fits.getval(myfile, 'EXPTIME', ext=1) < 220.:
        LMPDUR1 = 30.0
        LMP_ON1 = 0.0
        LMPOFF1 = 30.0
        LMPMED1 = 15.00000
        LMPDUR2 = 30.0
        LMP_ON2 = 60.0
        LMPOFF2 = 90.0
        LMPMED2 = 75.00000
        fits.setval(myfile, 'LMPDUR1', value=LMPDUR1, ext=1)
        fits.setval(myfile, 'LMP_ON1', value=LMP_ON1, ext=1)
        fits.setval(myfile, 'LMPOFF1', value=LMPOFF1, ext=1)
        fits.setval(myfile, 'LMPMED1', value=LMPMED1, ext=1)
        fits.setval(myfile, 'LMPDUR2', value=LMPDUR2, ext=1)
        fits.setval(myfile, 'LMP_ON2', value=LMP_ON2, ext=1)
        fits.setval(myfile, 'LMPOFF2', value=LMPOFF2, ext=1)
        fits.setval(myfile, 'LMPMED2', value=LMPMED2, ext=1)
        fits.setval(myfile, 'NUMFLASH', value=4, ext=1)
        fits.setval(myfile, 'TAGFLASH', value='UNIFORMLY SPACED', ext=0)
    elif fits.getval(myfile, 'OPT_ELEM') == 'G130M' and fits.getval(myfile, 'EXPTIME', ext=1) > 220.:
        LMPDUR1 = 30.0
        LMP_ON1 = 0.0
        LMPOFF1 = 30.0
        LMPMED1 = 15.00000
        LMPDUR2 = 30.0
        LMP_ON2 = 120.0
        LMPOFF2 = 150.0
        LMPMED2 = 135.00000
        fits.setval(myfile, 'LMPDUR1', value=LMPDUR1, ext=1)
        fits.setval(myfile, 'LMP_ON1', value=LMP_ON1, ext=1)
        fits.setval(myfile, 'LMPOFF1', value=LMPOFF1, ext=1)
        fits.setval(myfile, 'LMPMED1', value=LMPMED1, ext=1)
        fits.setval(myfile, 'LMPDUR2', value=LMPDUR2, ext=1)
        fits.setval(myfile, 'LMP_ON2', value=LMP_ON2, ext=1)
        fits.setval(myfile, 'LMPOFF2', value=LMPOFF2, ext=1)
        fits.setval(myfile, 'LMPMED2', value=LMPMED2, ext=1)
        fits.setval(myfile, 'NUMFLASH', value=12, ext=1)
        fits.setval(myfile, 'TAGFLASH', value='UNIFORMLY SPACED', ext=0)
    elif fits.getval(myfile, 'OPT_ELEM') == 'G140L' and fits.getval(myfile, 'EXPTIME', ext=1) < 460.:
        LMPDUR1 = 30.0
        LMP_ON1 = 0.0
        LMPOFF1 = 30.0
        LMPMED1 = 15.00000
        LMPDUR2 = 30.0
        LMP_ON2 = 60.0
        LMPOFF2 = 90.0
        LMPMED2 = 75.00000
        fits.setval(myfile, 'LMPDUR1', value=LMPDUR1, ext=1)
        fits.setval(myfile, 'LMP_ON1', value=LMP_ON1, ext=1)
        fits.setval(myfile, 'LMPOFF1', value=LMPOFF1, ext=1)
        fits.setval(myfile, 'LMPMED1', value=LMPMED1, ext=1)
        fits.setval(myfile, 'LMPDUR2', value=LMPDUR2, ext=1)
        fits.setval(myfile, 'LMP_ON2', value=LMP_ON2, ext=1)
        fits.setval(myfile, 'LMPOFF2', value=LMPOFF2, ext=1)
        fits.setval(myfile, 'LMPMED2', value=LMPMED2, ext=1)
        fits.setval(myfile, 'NUMFLASH', value=8, ext=1)
        fits.setval(myfile, 'TAGFLASH', value='UNIFORMLY SPACED', ext=0)
    elif fits.getval(myfile, 'OPT_ELEM') == 'G140L' and fits.getval(myfile, 'EXPTIME', ext=1) > 460.:
        LMPDUR1 = 30.0
        LMP_ON1 = 0.0
        LMPOFF1 = 30.0
        LMPMED1 = 15.00000
        LMPDUR2 = 30.0
        LMP_ON2 = 120.0
        LMPOFF2 = 150.0
        LMPMED2 = 135.00000
        fits.setval(myfile, 'LMPDUR1', value=LMPDUR1, ext=1)
        fits.setval(myfile, 'LMP_ON1', value=LMP_ON1, ext=1)
        fits.setval(myfile, 'LMPOFF1', value=LMPOFF1, ext=1)
        fits.setval(myfile, 'LMPMED1', value=LMPMED1, ext=1)
        fits.setval(myfile, 'LMPDUR2', value=LMPDUR2, ext=1)
        fits.setval(myfile, 'LMP_ON2', value=LMP_ON2, ext=1)
        fits.setval(myfile, 'LMPOFF2', value=LMPOFF2, ext=1)
        fits.setval(myfile, 'LMPMED2', value=LMPMED2, ext=1)
        fits.setval(myfile, 'NUMFLASH', value=15, ext=1)
        fits.setval(myfile, 'TAGFLASH', value='UNIFORMLY SPACED', ext=0)


In [16]:
# run CalCOS!!!

# let's glob only rawtag_a files because CalCOS has a weird thing about automatically
# processing rawtag_b files, then crashing when it sees a rawtag_b file

rawtagsa = glob.glob('*_rawtag_a.fits')

# now I'm actually going to run CalCOS on my data, outputting to
# the new output directory I made specified by "outdir"

for myfile in rawtagsa:
    calcos.calcos(myfile, outdir='/Users/ahirschauer/Documents/Year4/04-2021/Lamp_Tabs/ahirscha58916/output2')

# ^ the above is commented out so I don't accidentally run CalCOS again,
# since it takes like 20 minutes
# (unless you have to)

CALCOS version 3.3.10
numpy version 1.19.2
astropy version 4.2.1
Begin 21-Apr-2021 15:13:07 EDT
Input file = leih01ehq_rawtag_a.fits
Info:  aperture plate is offset by 65.08 pixels
    EXPTYPE will be changed to EXTERNAL/CAL.
Info:  aperture plate is offset by 65.08 pixels
    EXPTYPE will be changed to EXTERNAL/CAL.

TIME-TAG calibration -- 21-Apr-2021 15:13:10 EDT
Input     leih01ehq_rawtag_a.fits
OutTag    /Users/ahirschauer/Documents/Year4/04-2021/Lamp_Tabs/ahirscha58916/output/leih01ehq_corrtag_a.fits
OutFlt    /Users/ahirschauer/Documents/Year4/04-2021/Lamp_Tabs/ahirscha58916/output/leih01ehq_flt_a.fits
OutCounts /Users/ahirschauer/Documents/Year4/04-2021/Lamp_Tabs/ahirscha58916/output/leih01ehq_counts_a.fits
OutFlash  /Users/ahirschauer/Documents/Year4/04-2021/Lamp_Tabs/ahirscha58916/output/leih01ehq_lampflash_a.fits
DETECTOR  FUV, segment A
EXPTYPE   EXTERNAL/CAL
OPT_ELEM  G130M, CENWAVE 1291, FPOFFSET 0
APERTURE  WCA

BADTCORR  OMIT
RANDCORR  PERFORM
RANDSEED = 123456789
TEMPC

DEADCORR  PERFORM
DEADTAB = lref$s7g1700gl_dead.fits
PHACORR   PERFORM
PHATAB  = lref$wc318317l_pha.fits
DOPPCORR  OMIT
FLATCORR  OMIT
WAVECORR  PERFORM
Process tagflash wavecal
WCPTAB  = lref$u1t1616ql_wcp.fits
LAMPTAB = lref$23n1744jl_lamp.fits
XTRACTAB= lref$x1v17414l_1dx.fits
DISPTAB = lref$xaa18189l_disp.fits
lamp on, off, duration, median time:
1:  0.7  30.7  30.0  15.3
2:  60.7  90.5  29.8  75.7
3:  120.7  150.7  30.0  135.5
4:  180.7  210.0  29.4  195.1
  segment    cross-disp           dispersion direction
            shift (locn)      shift err  [orig.]    FP   chi sq (n)
  -------   -------------     -------------------------  ----------
 1 FUVA      59.1 (650.4)      34.8 0.52 [ 34.8]    0.0  9464.1 (4092)
 2 FUVA      59.0 (650.3)      34.2 0.54 [ 34.2]    0.0  9797.2 (4097)
 3 FUVA      59.1 (650.4)      34.0 0.53 [ 34.0]    0.0  9552.6 (4083)
 4 FUVA      59.0 (650.4)      33.6 0.77 [ 33.6]    0.0  9301.6 (4082)
LAMPUSED = NONE, which is incorrect; the value will be rese

HELCORR   OMIT for computing wavelengths for the corrtag table
BRSTCORR  OMIT
TRCECORR  OMIT
ALGNCORR  OMIT
DQICORR   PERFORM
BPIXTAB = lref$36d1836ml_bpix.fits
GSAGTAB = lref$54c1542dl_gsag.fits
SPOTTAB = lref$zas1615jl_spot.fits
STATFLAG  T
Append a TIMELINE extension.
X1DCORR   OMIT
End   21-Apr-2021 15:16:16 EDT
CALCOS version 3.3.10
numpy version 1.19.2
astropy version 4.2.1
Begin 21-Apr-2021 15:16:16 EDT
Input file = leih03iiq_rawtag_a.fits
    EXPTYPE will be changed to EXTERNAL/CAL.

TIME-TAG calibration -- 21-Apr-2021 15:16:17 EDT
Input     leih03iiq_rawtag_a.fits
OutTag    /Users/ahirschauer/Documents/Year4/04-2021/Lamp_Tabs/ahirscha58916/output/leih03iiq_corrtag_a.fits
OutFlt    /Users/ahirschauer/Documents/Year4/04-2021/Lamp_Tabs/ahirscha58916/output/leih03iiq_flt_a.fits
OutCounts /Users/ahirschauer/Documents/Year4/04-2021/Lamp_Tabs/ahirscha58916/output/leih03iiq_counts_a.fits
OutFlash  /Users/ahirschauer/Documents/Year4/04-2021/Lamp_Tabs/ahirscha58916/output/leih03iiq_lamp

GSAGTAB = lref$54c1542dl_gsag.fits
SPOTTAB = lref$zas1615jl_spot.fits
STATFLAG  T
Append a TIMELINE extension.
X1DCORR   OMIT
End   21-Apr-2021 15:17:31 EDT
CALCOS version 3.3.10
numpy version 1.19.2
astropy version 4.2.1
Begin 21-Apr-2021 15:17:31 EDT
Input file = leih02c0q_rawtag_a.fits
Info:  aperture plate is offset by 65.08 pixels
    EXPTYPE will be changed to EXTERNAL/CAL.
Info:  aperture plate is offset by 65.08 pixels
    EXPTYPE will be changed to EXTERNAL/CAL.

TIME-TAG calibration -- 21-Apr-2021 15:17:31 EDT
Input     leih02c0q_rawtag_a.fits
OutTag    /Users/ahirschauer/Documents/Year4/04-2021/Lamp_Tabs/ahirscha58916/output/leih02c0q_corrtag_a.fits
OutFlt    /Users/ahirschauer/Documents/Year4/04-2021/Lamp_Tabs/ahirscha58916/output/leih02c0q_flt_a.fits
OutCounts /Users/ahirschauer/Documents/Year4/04-2021/Lamp_Tabs/ahirscha58916/output/leih02c0q_counts_a.fits
OutFlash  /Users/ahirschauer/Documents/Year4/04-2021/Lamp_Tabs/ahirscha58916/output/leih02c0q_lampflash_a.fits
DETECTO

OutCounts /Users/ahirschauer/Documents/Year4/04-2021/Lamp_Tabs/ahirscha58916/output/leih01f6q_counts_b.fits
OutFlash  /Users/ahirschauer/Documents/Year4/04-2021/Lamp_Tabs/ahirscha58916/output/leih01f6q_lampflash_b.fits
DETECTOR  FUV, segment B
EXPTYPE   EXTERNAL/CAL
OPT_ELEM  G130M, CENWAVE 1291, FPOFFSET 0
APERTURE  WCA

BADTCORR  OMIT
RANDCORR  PERFORM
RANDSEED = 123456789
TEMPCORR  PERFORM
BRFTAB  = lref$x1u1459il_brf.fits
GEOCORR   PERFORM
GEOFILE = lref$x1u1459gl_geo.fits
IGEOCORR  PERFORM
DGEOCORR  OMIT
XWLKCORR  PERFORM
XWLKFILE= lref$14o2013ql_xwalk.fits
YWLKCORR  PERFORM
YWLKFILE= lref$14o2013rl_ywalk.fits
DEADCORR  PERFORM
DEADTAB = lref$s7g1700gl_dead.fits
PHACORR   PERFORM
PHATAB  = lref$wc318317l_pha.fits
DOPPCORR  OMIT
FLATCORR  OMIT
WAVECORR  PERFORM
Process tagflash wavecal
WCPTAB  = lref$u1t1616ql_wcp.fits
LAMPTAB = lref$23n1744jl_lamp.fits
XTRACTAB= lref$x1v17414l_1dx.fits
DISPTAB = lref$xaa18189l_disp.fits
lamp on, off, duration, median time:
1:  0.5  30.5  30.0  15.

DEADTAB = lref$s7g1700gl_dead.fits
PHACORR   PERFORM
PHATAB  = lref$wc318317l_pha.fits
DOPPCORR  OMIT
FLATCORR  OMIT
WAVECORR  PERFORM
Process tagflash wavecal
WCPTAB  = lref$u1t1616ql_wcp.fits
LAMPTAB = lref$52j2110ml_lamp.fits
XTRACTAB= lref$52j2110kl_1dx.fits
DISPTAB = lref$52j2117ml_disp.fits
lamp on, off, duration, median time:
1:  0.8  30.8  30.0  16.1
2:  60.8  90.8  30.0  76.0
3:  121.8  150.6  28.8  136.4
4:  180.8  210.8  30.0  195.7
5:  241.8  270.8  29.0  256.5
6:  300.8  330.8  30.0  316.0
7:  360.8  390.8  30.0  375.6
8:  420.8  450.0  29.2  435.4
  segment    cross-disp           dispersion direction
            shift (locn)      shift err  [orig.]    FP   chi sq (n)
  -------   -------------     -------------------------  ----------
 1 FUVA       0.5 (564.8)       0.0 0.00 [  0.0]    0.0     0.0 (0)  # not found
 2 FUVA       0.5 (564.8)       0.0 4.57 [256.8]    0.0  19850229.5 (6127)  # not found
 3 FUVA       0.6 (564.9)       0.0 0.00 [  0.0]    0.0     0.0 (0)  # n

15 FUVA       0.1 (564.4)       0.0 0.00 [  0.0]    0.0     0.0 (0)  # not found
LAMPUSED = NONE, which is incorrect; the value will be reset to P1.
HELCORR   OMIT for computing wavelengths for the corrtag table
BRSTCORR  OMIT
TRCECORR  OMIT
ALGNCORR  OMIT
DQICORR   PERFORM
BPIXTAB = lref$36d1836ml_bpix.fits
GSAGTAB = lref$54c1542dl_gsag.fits
SPOTTAB = lref$zas1615jl_spot.fits
STATFLAG  T
Append a TIMELINE extension.
X1DCORR   OMIT
End   21-Apr-2021 15:21:09 EDT
CALCOS version 3.3.10
numpy version 1.19.2
astropy version 4.2.1
Begin 21-Apr-2021 15:21:09 EDT
Input file = leih02c2q_rawtag_a.fits
Info:  aperture plate is offset by 65.08 pixels
    EXPTYPE will be changed to EXTERNAL/CAL.
Info:  aperture plate is offset by 65.08 pixels
    EXPTYPE will be changed to EXTERNAL/CAL.

TIME-TAG calibration -- 21-Apr-2021 15:21:09 EDT
Input     leih02c2q_rawtag_a.fits
OutTag    /Users/ahirschauer/Documents/Year4/04-2021/Lamp_Tabs/ahirscha58916/output/leih02c2q_corrtag_a.fits
OutFlt    /Users/ahir

X1DCORR   OMIT

TIME-TAG calibration -- 21-Apr-2021 15:22:12 EDT
Input     leih01g8q_rawtag_b.fits
OutTag    /Users/ahirschauer/Documents/Year4/04-2021/Lamp_Tabs/ahirscha58916/output/leih01g8q_corrtag_b.fits
OutFlt    /Users/ahirschauer/Documents/Year4/04-2021/Lamp_Tabs/ahirscha58916/output/leih01g8q_flt_b.fits
OutCounts /Users/ahirschauer/Documents/Year4/04-2021/Lamp_Tabs/ahirscha58916/output/leih01g8q_counts_b.fits
OutFlash  /Users/ahirschauer/Documents/Year4/04-2021/Lamp_Tabs/ahirscha58916/output/leih01g8q_lampflash_b.fits
DETECTOR  FUV, segment B
EXPTYPE   EXTERNAL/CAL
OPT_ELEM  G130M, CENWAVE 1300, FPOFFSET 1
APERTURE  WCA

BADTCORR  OMIT
RANDCORR  PERFORM
RANDSEED = 123456789
TEMPCORR  PERFORM
BRFTAB  = lref$x1u1459il_brf.fits
GEOCORR   PERFORM
GEOFILE = lref$x1u1459gl_geo.fits
IGEOCORR  PERFORM
DGEOCORR  OMIT
XWLKCORR  PERFORM
XWLKFILE= lref$14o2013ql_xwalk.fits
YWLKCORR  PERFORM
YWLKFILE= lref$14o2013rl_ywalk.fits
DEADCORR  PERFORM
DEADTAB = lref$s7g1700gl_dead.fits
PHACORR   P

OutFlash  /Users/ahirschauer/Documents/Year4/04-2021/Lamp_Tabs/ahirscha58916/output/leih02c4q_lampflash_a.fits
DETECTOR  FUV, segment A
EXPTYPE   EXTERNAL/CAL
OPT_ELEM  G130M, CENWAVE 1318, FPOFFSET 0
APERTURE  WCA

BADTCORR  OMIT
RANDCORR  PERFORM
RANDSEED = 123456789
TEMPCORR  PERFORM
BRFTAB  = lref$x1u1459il_brf.fits
GEOCORR   PERFORM
GEOFILE = lref$x1u1459gl_geo.fits
IGEOCORR  PERFORM
DGEOCORR  OMIT
XWLKCORR  PERFORM
XWLKFILE= lref$14o2013ql_xwalk.fits
YWLKCORR  PERFORM
YWLKFILE= lref$14o2013rl_ywalk.fits
DEADCORR  PERFORM
DEADTAB = lref$s7g1700gl_dead.fits
PHACORR   PERFORM
PHATAB  = lref$wc318317l_pha.fits
DOPPCORR  OMIT
FLATCORR  OMIT
WAVECORR  PERFORM
Process tagflash wavecal
WCPTAB  = lref$u1t1616ql_wcp.fits
LAMPTAB = lref$23n1744jl_lamp.fits
XTRACTAB= lref$x1v17414l_1dx.fits
DISPTAB = lref$xaa18189l_disp.fits
lamp on, off, duration, median time:
1:  0.7  30.7  30.0  15.4
2:  60.7  90.5  29.8  75.6
3:  120.7  150.7  30.0  135.5
4:  180.7  210.0  29.3  195.5
  segment    cross-

  segment    cross-disp           dispersion direction
            shift (locn)      shift err  [orig.]    FP   chi sq (n)
  -------   -------------     -------------------------  ----------
 1 FUVB      61.1 (707.2)     405.2 0.57 [133.7]  271.5  7362.2 (3482)
 2 FUVB      61.1 (707.3)     405.2 0.93 [133.8]  271.5  7443.6 (3483)
 3 FUVB      61.1 (707.2)     405.2 0.65 [133.7]  271.5  7111.4 (3402)
 4 FUVB      61.1 (707.3)     405.3 0.49 [133.8]  271.5  7524.1 (3455)
LAMPUSED = NONE, which is incorrect; the value will be reset to P1.
HELCORR   OMIT for computing wavelengths for the corrtag table
BRSTCORR  OMIT
TRCECORR  OMIT
ALGNCORR  OMIT
DQICORR   PERFORM
BPIXTAB = lref$36d1836ml_bpix.fits
GSAGTAB = lref$54c1542dl_gsag.fits
SPOTTAB = lref$zas1615jl_spot.fits
STATFLAG  T
Append a TIMELINE extension.
X1DCORR   OMIT
End   21-Apr-2021 15:24:34 EDT
CALCOS version 3.3.10
numpy version 1.19.2
astropy version 4.2.1
Begin 21-Apr-2021 15:24:34 EDT
Input file = leih02bbq_rawtag_a.fits
Info: 


TIME-TAG calibration -- 21-Apr-2021 15:25:39 EDT
Input     leih01geq_rawtag_a.fits
OutTag    /Users/ahirschauer/Documents/Year4/04-2021/Lamp_Tabs/ahirscha58916/output/leih01geq_corrtag_a.fits
OutFlt    /Users/ahirschauer/Documents/Year4/04-2021/Lamp_Tabs/ahirscha58916/output/leih01geq_flt_a.fits
OutCounts /Users/ahirschauer/Documents/Year4/04-2021/Lamp_Tabs/ahirscha58916/output/leih01geq_counts_a.fits
OutFlash  /Users/ahirschauer/Documents/Year4/04-2021/Lamp_Tabs/ahirscha58916/output/leih01geq_lampflash_a.fits
DETECTOR  FUV, segment A
EXPTYPE   EXTERNAL/CAL
OPT_ELEM  G130M, CENWAVE 1309, FPOFFSET -1
APERTURE  WCA

BADTCORR  OMIT
RANDCORR  PERFORM
RANDSEED = 123456789
TEMPCORR  PERFORM
BRFTAB  = lref$x1u1459il_brf.fits
GEOCORR   PERFORM
GEOFILE = lref$x1u1459gl_geo.fits
IGEOCORR  PERFORM
DGEOCORR  OMIT
XWLKCORR  PERFORM
XWLKFILE= lref$14o2013ql_xwalk.fits
YWLKCORR  PERFORM
YWLKFILE= lref$14o2013rl_ywalk.fits
DEADCORR  PERFORM
DEADTAB = lref$s7g1700gl_dead.fits
PHACORR   PERFORM
PHATAB 

PHACORR   PERFORM
PHATAB  = lref$wc318317l_pha.fits
DOPPCORR  OMIT
FLATCORR  OMIT
WAVECORR  PERFORM
Process tagflash wavecal
WCPTAB  = lref$u1t1616ql_wcp.fits
LAMPTAB = lref$23n1744jl_lamp.fits
XTRACTAB= lref$x1v17414l_1dx.fits
DISPTAB = lref$xaa18189l_disp.fits
lamp on, off, duration, median time:
1:  0.7  30.7  30.0  15.3
2:  60.7  90.7  30.0  75.7
3:  120.7  150.5  29.8  135.6
4:  180.7  210.0  29.3  195.5
  segment    cross-disp           dispersion direction
            shift (locn)      shift err  [orig.]    FP   chi sq (n)
  -------   -------------     -------------------------  ----------
 1 FUVB      61.2 (707.3)      23.8 0.62 [ 23.8]    0.0  6924.5 (3429)
 2 FUVB      61.1 (707.2)      23.3 0.80 [ 23.3]    0.0  6920.8 (3423)
 3 FUVB      61.1 (707.2)      23.0 0.73 [ 23.0]    0.0  6968.5 (3391)
 4 FUVB      61.2 (707.3)      22.8 0.42 [ 22.8]    0.0  6966.3 (3465)
LAMPUSED = NONE, which is incorrect; the value will be reset to P1.
HELCORR   OMIT for computing wavelengths for

LAMPTAB = lref$23n1744jl_lamp.fits
XTRACTAB= lref$x1v17414l_1dx.fits
DISPTAB = lref$xaa18189l_disp.fits
lamp on, off, duration, median time:
1:  0.5  30.5  30.0  15.9
2:  60.5  90.5  30.0  75.7
3:  120.5  150.5  30.0  135.9
4:  180.5  210.0  29.5  195.6
  segment    cross-disp           dispersion direction
            shift (locn)      shift err  [orig.]    FP   chi sq (n)
  -------   -------------     -------------------------  ----------
 1 FUVB      61.0 (707.2)     -56.5 1.11 [104.7] -161.2  7003.1 (3315)
 2 FUVB      61.0 (707.2)     -56.6 0.73 [104.6] -161.2  7209.5 (3336)
 3 FUVB      61.0 (707.2)     -56.9 0.57 [104.2] -161.2  7149.7 (3328)
 4 FUVB      61.1 (707.2)     -57.0 0.66 [104.2] -161.2  7314.8 (3342)
LAMPUSED = NONE, which is incorrect; the value will be reset to P1.
HELCORR   OMIT for computing wavelengths for the corrtag table
BRSTCORR  OMIT
TRCECORR  OMIT
ALGNCORR  OMIT
DQICORR   PERFORM
BPIXTAB = lref$36d1836ml_bpix.fits
GSAGTAB = lref$54c1542dl_gsag.fits
SPOTTAB

 1 FUVA      59.1 (651.0)    -473.1 0.76 [ 21.1] -494.2  8309.9 (4024)
 2 FUVA      59.2 (651.1)    -473.6 0.77 [ 20.5] -494.2  8248.6 (4001)
 3 FUVA      59.3 (651.2)    -473.8 0.82 [ 20.4] -494.2  7936.5 (3992)
 4 FUVA      59.2 (651.1)    -473.9 0.73 [ 20.2] -494.2  8349.0 (3984)
LAMPUSED = NONE, which is incorrect; the value will be reset to P1.
HELCORR   OMIT for computing wavelengths for the corrtag table
BRSTCORR  OMIT
TRCECORR  OMIT
ALGNCORR  OMIT
DQICORR   PERFORM
BPIXTAB = lref$36d1836ml_bpix.fits
GSAGTAB = lref$54c1542dl_gsag.fits
SPOTTAB = lref$zas1615jl_spot.fits
STATFLAG  T
Append a TIMELINE extension.
X1DCORR   OMIT

TIME-TAG calibration -- 21-Apr-2021 15:29:13 EDT
Input     leih01euq_rawtag_b.fits
OutTag    /Users/ahirschauer/Documents/Year4/04-2021/Lamp_Tabs/ahirscha58916/output/leih01euq_corrtag_b.fits
OutFlt    /Users/ahirschauer/Documents/Year4/04-2021/Lamp_Tabs/ahirscha58916/output/leih01euq_flt_b.fits
OutCounts /Users/ahirschauer/Documents/Year4/04-2021/Lamp_Tabs/

    EXPTYPE will be changed to EXTERNAL/CAL.
Info:  aperture plate is offset by 65.08 pixels
    EXPTYPE will be changed to EXTERNAL/CAL.

TIME-TAG calibration -- 21-Apr-2021 15:30:15 EDT
Input     leih01fbq_rawtag_a.fits
OutTag    /Users/ahirschauer/Documents/Year4/04-2021/Lamp_Tabs/ahirscha58916/output/leih01fbq_corrtag_a.fits
OutFlt    /Users/ahirschauer/Documents/Year4/04-2021/Lamp_Tabs/ahirscha58916/output/leih01fbq_flt_a.fits
OutCounts /Users/ahirschauer/Documents/Year4/04-2021/Lamp_Tabs/ahirscha58916/output/leih01fbq_counts_a.fits
OutFlash  /Users/ahirschauer/Documents/Year4/04-2021/Lamp_Tabs/ahirscha58916/output/leih01fbq_lampflash_a.fits
DETECTOR  FUV, segment A
EXPTYPE   EXTERNAL/CAL
OPT_ELEM  G130M, CENWAVE 1291, FPOFFSET 1
APERTURE  WCA

BADTCORR  OMIT
RANDCORR  PERFORM
RANDSEED = 123456789
TEMPCORR  PERFORM
BRFTAB  = lref$x1u1459il_brf.fits
GEOCORR   PERFORM
GEOFILE = lref$x1u1459gl_geo.fits
IGEOCORR  PERFORM
DGEOCORR  OMIT
XWLKCORR  PERFORM
XWLKFILE= lref$14o2013ql_xwalk.

IGEOCORR  PERFORM
DGEOCORR  OMIT
XWLKCORR  PERFORM
XWLKFILE= lref$14o2013ql_xwalk.fits
YWLKCORR  PERFORM
YWLKFILE= lref$14o2013rl_ywalk.fits
DEADCORR  PERFORM
DEADTAB = lref$s7g1700gl_dead.fits
PHACORR   PERFORM
PHATAB  = lref$wc318317l_pha.fits
DOPPCORR  OMIT
FLATCORR  OMIT
WAVECORR  PERFORM
Process tagflash wavecal
WCPTAB  = lref$u1t1616ql_wcp.fits
LAMPTAB = lref$23n1744jl_lamp.fits
XTRACTAB= lref$x1v17414l_1dx.fits
DISPTAB = lref$xaa18189l_disp.fits
lamp on, off, duration, median time:
1:  0.6  30.4  29.8  15.3
2:  60.6  90.6  30.0  75.8
3:  120.6  150.6  30.0  135.1
4:  180.6  210.0  29.4  195.1
  segment    cross-disp           dispersion direction
            shift (locn)      shift err  [orig.]    FP   chi sq (n)
  -------   -------------     -------------------------  ----------
 1 FUVB      61.2 (709.5)     -50.5 4.16 [185.7] -236.2  5617.4 (2470)
 2 FUVB      61.1 (709.4)     -50.7 0.99 [185.5] -236.2  5067.2 (2462)
 3 FUVB      61.3 (709.6)     -50.1 5.67 [186.1] -236.2  528

In [19]:
# let's take a look at one of the lampflash files

# here I'm selecting one from my output directory totally at random
# whoops that was a lot, let's change this...

data = fits.getdata('leih01gaq_lampflash.fits')

In [20]:
# what are all the column names in the lampflash file?

data.columns

ColDefs(
    name = 'SEGMENT'; format = '4A'
    name = 'TIME'; format = '1D'; unit = 's'; disp = 'F8.3'
    name = 'EXPTIME'; format = '1D'; unit = 's'; disp = 'F8.3'
    name = 'LAMP_ON'; format = '1D'; unit = 's'; disp = 'F8.3'
    name = 'LAMP_OFF'; format = '1D'; unit = 's'; disp = 'F8.3'
    name = 'NELEM'; format = '1J'; disp = 'I6'
    name = 'WAVELENGTH'; format = '16384D'; unit = 'angstrom'
    name = 'NET'; format = '16384E'; unit = 'count /s'
    name = 'GROSS'; format = '16384E'; unit = 'count /s'
    name = 'BACKGROUND'; format = '16384E'; unit = 'count /s'
    name = 'SHIFT_DISP'; format = '1E'; unit = 'pixel'
    name = 'SHIFT_XDISP'; format = '1E'; unit = 'pixel'
    name = 'SPEC_FOUND'; format = '1L'
    name = 'CHI_SQUARE'; format = '1E'
    name = 'N_DEG_FREEDOM'; format = '1J'; disp = 'I5'
)

In [21]:
# show me the data from the SHIFT_DISP column

data['SHIFT_DISP']

# we see eight output values, each corresponding to one lamp flash from
# what must be one of the G140L/800 observations, from one of the FP-POS

array([-433.7379 , -433.9637 , -434.30478, -434.42685, -433.29044,
       -433.46817, -433.9612 , -434.0909 ], dtype=float32)

In [40]:
# now we check the existing Lamp Tab here:
# https://hst-crds.stsci.edu/
# and we go to COS, then lamptab, finding the current one for LP4, which is
# https://hst-crds.stsci.edu/browse/2bj2256ol_lamp.fits

# we need to get rid of the fp pixel shift values that we're seeing
# since we don't have those yet for LP5, we're using LP4 as a guess
# since they probably don't change very much for each LP

# NB LP4 has what we need for G140L/800, which we're doing now
# also note that LP5 is close to LP2, but there is no lamptab for LP2
# (it uses the lamptab file for LP1)

# this won't be perfect, but we'll be pretty close

# okay, now we have to *get* the file, which you can't download from the website

# $lref is our COS reference file folder, which is located at:
# /grp/hst/cdbs/lref/

# (you can CD into this directory if you're on the VPN, then CP to wherever)

# now open the LampTab, open the row for cenwave 800, and locate the FP pixel shift
# for all for FP-POS
# (we're interested in cenwave 800 since our randomly-selected file is that)

lampdata4 = fits.getdata('LP4_LampTab.fits')

In [41]:
# what columns are in the new variable "lampdata"?

lampdata4.columns

ColDefs(
    name = 'SEGMENT'; format = '4A'; disp = 'A4'
    name = 'OPT_ELEM'; format = '5A'; disp = 'A8'
    name = 'CENWAVE'; format = 'J'; unit = 'angstrom'; disp = 'I5'
    name = 'FPOFFSET'; format = 'J'; unit = 'steps'; disp = 'I5'
    name = 'HAS_LINES'; format = 'L'; disp = 'L1'
    name = 'FP_PIXEL_SHIFT'; format = 'D'; disp = 'G15.7'
    name = 'INTENSITY'; format = '16384D'
)

In [42]:
# we are selecting (using numpy) from files of G140L and 800

sel4 = np.where((lampdata4['OPT_ELEM'] == 'G140L') & (lampdata4['CENWAVE'] == 800))

# and now selecting the lampdata from what we defined as "sel", both the FP offset
# and the fp pixel shift (not sure of the formatting yet though)

lampdata4[sel4]['FPOFFSET'], lampdata4[sel4]['FP_PIXEL_SHIFT']

# hmm, it looks like the FP-POS = 1 FP_PIXEL_SHIFT is off by ~50 pixels
# compared to what we saw earlier...

(array([-2, -1,  0,  1], dtype=int32),
 array([-485.11078455, -214.06629603,    0.        ,  277.24091168]))

In [43]:
# let's take a look at the LP3 lamptab file...

lampdata3 = fits.getdata('LP3_LampTab.fits')

In [44]:
lampdata3.columns

ColDefs(
    name = 'SEGMENT'; format = '4A'; disp = 'A4'
    name = 'OPT_ELEM'; format = '5A'; disp = 'A8'
    name = 'CENWAVE'; format = 'J'; unit = 'angstrom'; disp = 'I5'
    name = 'FPOFFSET'; format = 'J'; unit = 'steps'; disp = 'I5'
    name = 'HAS_LINES'; format = 'L'; disp = 'L1'
    name = 'FP_PIXEL_SHIFT'; format = 'D'; disp = 'G15.7'
    name = 'INTENSITY'; format = '16384D'
)

In [45]:
sel3 = np.where((lampdata3['OPT_ELEM'] == 'G140L') & (lampdata3['CENWAVE'] == 1105))

lampdata3[sel3]['FPOFFSET'], lampdata3[sel3]['FP_PIXEL_SHIFT']

(array([-2, -1,  0,  1], dtype=int32),
 array([-517.44628131, -255.17912466,    0.        ,  235.57090234]))

In [46]:
# okay so we checked where the FP pixel shift would be expected at LP3
# but for G140L/1105 (since cenwave 800 doesn't exist here yet)
# and we found that the "expected" shift is even more different!

# let's now take a look at one of the _lampflash.fits files for G130M
# from my program's dataset and compare that to the LP4 lampflash file

data2 = fits.getdata('leih01f6q_lampflash.fits')

# this one is a G130M lampflash file

In [47]:
data2.columns

ColDefs(
    name = 'SEGMENT'; format = '4A'
    name = 'TIME'; format = '1D'; unit = 's'; disp = 'F8.3'
    name = 'EXPTIME'; format = '1D'; unit = 's'; disp = 'F8.3'
    name = 'LAMP_ON'; format = '1D'; unit = 's'; disp = 'F8.3'
    name = 'LAMP_OFF'; format = '1D'; unit = 's'; disp = 'F8.3'
    name = 'NELEM'; format = '1J'; disp = 'I6'
    name = 'WAVELENGTH'; format = '16384D'; unit = 'angstrom'
    name = 'NET'; format = '16384E'; unit = 'count /s'
    name = 'GROSS'; format = '16384E'; unit = 'count /s'
    name = 'BACKGROUND'; format = '16384E'; unit = 'count /s'
    name = 'SHIFT_DISP'; format = '1E'; unit = 'pixel'
    name = 'SHIFT_XDISP'; format = '1E'; unit = 'pixel'
    name = 'SPEC_FOUND'; format = '1L'
    name = 'CHI_SQUARE'; format = '1E'
    name = 'N_DEG_FREEDOM'; format = '1J'; disp = 'I5'
)

In [48]:
data2['SHIFT_DISP']

array([63.877857, 63.45603 , 63.402016, 63.481426, 58.947098, 58.388226,
       58.38295 , 58.561092], dtype=float32)

In [49]:
data2['SEGMENT']

chararray(['FUVA', 'FUVA', 'FUVA', 'FUVA', 'FUVB', 'FUVB', 'FUVB', 'FUVB'],
          dtype='<U4')

In [50]:
# we wanted to figure out which cenwave we're looking at (it's 1291)

#fits.getheader('leih01f6q_lampflash.fits')

In [53]:
# what we're seeing is that there are four flashes, but now two segments,
# whereas with G140L there were eight flashes on one segment.
# what a coincidence!

# let's compare these to the LP4 lamp flash file

sel2 = np.where((lampdata4['OPT_ELEM'] == 'G130M') & (lampdata4['CENWAVE'] == 1291) & (lampdata4['SEGMENT'] == 'FUVA'))

lampdata4[sel2]['FPOFFSET'], lampdata4[sel2]['FP_PIXEL_SHIFT']

(array([-2, -1,  0,  1], dtype=int32),
 array([-519.2847117 , -197.7793916 ,    0.        ,  291.77080735]))

In [ ]:
# the numbers we're seeing for the pixel shift aren't similar to what we see in the
# older LampTab files, but keep in mind that the data we're seeing for this program
# is probing parameter space that hasn't been looked at before, so it shouldn't be a
# surprise if the pixel offsets are different compared to other LPs.

# we're going to be comparing the pixel shifts relative to each other, not compared to
# the other (older) LPs, so whatever values we get is what we get, end of story!

# maybe this is why they made the placeholder LampTab files now?

